services:
  web:
    build: .
    ports:
      - 80:80
      - 443:443
    # volumes:
    #   - ./web:/usr/share/nginx/html
    #   - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  
volumes:
  web: